### Olá! Eu sou milenafaria ❤
- Estudando Enhenharia de Computação
- IFSULDEMINAS 5° Período
- Estudando JavaScript
- Contate-me no email: milenafaria1706@gmail.com

 <div>
  <a href="https://github.com/milenafaria">
  <img height="180em" src="https://github-readme-stats.vercel.app/api?username=petertrento&show_icons=true&theme=dracula&include_all_commits=true&count_private=true"/>
  

